---
-
  name: check  status of the service and email if its down
  hosts: win
  var:
    dns_server: 1.1.1.1

  tasks:
  - name: Copy File
    command: service httpd status
# ask Ansible do not collect the FACT data from server.
      gather_factx: no
# this is output
    register: result
  -mail:
    to: hello@abc.com
    subject: ccc
    body: httpd service is dwown
    when: result.stdout.find('down') !=-1
    # return the result and the FACTS
  - debug:
   var: result
   var: ansible_facts
   line: 'nameserver {{dns_server}}'
   port: '{{htt_port}}'
      
   loop: "{{}}"     
        
      
# the command run with parameter
> Web http_port=1234

# jinja2 templating.
# -v is another way to display the output.


# variable precedence. 
(Extra vars(cmd)) > Set Facts > include Vars > Role Vars > (Play) > (Host) > ( Group Vars) > Role Default.

