---
- name: testing
  hosts: win 
  tasks: 
  - name: Windows command
    win_command: whoami 
    register: whoami_output
  - name: pritn the output
    debug: 
      msg: "this is {{whoami_output.stdout}}"
      
https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_file_module.html
